spring:
    datasource:
        url: your url...
        username: your username...
        password: your password...
        driver-class-name: your driver...
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                dialect: todo...
